title: SDM366 Optimal Control and Estimation
description: SUSTech 2024 Spring SDM366 course website
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
