title: SUSTech SDM366
description: SUSTech 2024 Spring SDM366 Optimal Control and Estimation course website
theme: just-the-docs

url: https://clearlab-sustech.github.io/SDM366-Sp24/

aux_links:
  # Template Repository: https://github.com/just-the-docs/just-the-docs-template
